name: Pull Request

on: pull_request

jobs:
  conventional:
    runs-on: ubuntu-latest

    steps:
      - name: Conventional PR
        uses: Namchee/conventional-pr@v0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
